// Languages offered when adding one in Settings. Codes are the two-letter ISO
// 639-1 codes the speech recognizer and Piper voices use.

export interface KnownLanguage {
  code: string;
  /** English name: used in prompts ("Always respond in French"). */
  name: string;
  native: string;
  direction: "ltr" | "rtl";
}

const RTL = new Set(["ar", "dv", "fa", "he", "ps", "sd", "ug", "ur", "yi"]);

const LIST: [string, string, string][] = [
  ["en", "English", "English"],
  ["zh", "Chinese", "中文"],
  ["es", "Spanish", "Español"],
  ["fr", "French", "Français"],
  ["pt", "Portuguese", "Português"],
  ["ru", "Russian", "Русский"],
  ["ja", "Japanese", "日本語"],
  ["ko", "Korean", "한국어"],
  ["it", "Italian", "Italiano"],
  ["tr", "Turkish", "Türkçe"],
  ["nl", "Dutch", "Nederlands"],
  ["pl", "Polish", "Polski"],
  ["sv", "Swedish", "Svenska"],
  ["no", "Norwegian", "Norsk"],
  ["da", "Danish", "Dansk"],
  ["fi", "Finnish", "Suomi"],
  ["el", "Greek", "Ελληνικά"],
  ["cs", "Czech", "Čeština"],
  ["sk", "Slovak", "Slovenčina"],
  ["sl", "Slovenian", "Slovenščina"],
  ["hr", "Croatian", "Hrvatski"],
  ["sr", "Serbian", "Српски"],
  ["bs", "Bosnian", "Bosanski"],
  ["bg", "Bulgarian", "Български"],
  ["ro", "Romanian", "Română"],
  ["hu", "Hungarian", "Magyar"],
  ["uk", "Ukrainian", "Українська"],
  ["be", "Belarusian", "Беларуская"],
  ["lt", "Lithuanian", "Lietuvių"],
  ["lv", "Latvian", "Latviešu"],
  ["et", "Estonian", "Eesti"],
  ["is", "Icelandic", "Íslenska"],
  ["ga", "Irish", "Gaeilge"],
  ["cy", "Welsh", "Cymraeg"],
  ["ca", "Catalan", "Català"],
  ["eu", "Basque", "Euskara"],
  ["gl", "Galician", "Galego"],
  ["mt", "Maltese", "Malti"],
  ["sq", "Albanian", "Shqip"],
  ["mk", "Macedonian", "Македонски"],
  ["hy", "Armenian", "Հայերեն"],
  ["ka", "Georgian", "ქართული"],
  ["az", "Azerbaijani", "Azərbaycanca"],
  ["kk", "Kazakh", "Қазақша"],
  ["uz", "Uzbek", "Oʻzbekcha"],
  ["mn", "Mongolian", "Монгол"],
  ["he", "Hebrew", "עברית"],
  ["fa", "Persian", "فارسی"],
  ["ur", "Urdu", "اردو"],
  ["ps", "Pashto", "پښتو"],
  ["hi", "Hindi", "हिन्दी"],
  ["bn", "Bengali", "বাংলা"],
  ["pa", "Punjabi", "ਪੰਜਾਬੀ"],
  ["gu", "Gujarati", "ગુજરાતી"],
  ["mr", "Marathi", "मराठी"],
  ["ta", "Tamil", "தமிழ்"],
  ["te", "Telugu", "తెలుగు"],
  ["kn", "Kannada", "ಕನ್ನಡ"],
  ["ml", "Malayalam", "മലയാളം"],
  ["si", "Sinhala", "සිංහල"],
  ["ne", "Nepali", "नेपाली"],
  ["th", "Thai", "ไทย"],
  ["vi", "Vietnamese", "Tiếng Việt"],
  ["id", "Indonesian", "Bahasa Indonesia"],
  ["ms", "Malay", "Bahasa Melayu"],
  ["tl", "Filipino", "Filipino"],
  ["km", "Khmer", "ខ្មែរ"],
  ["lo", "Lao", "ລາວ"],
  ["my", "Burmese", "မြန်မာ"],
  ["sw", "Swahili", "Kiswahili"],
  ["am", "Amharic", "አማርኛ"],
  ["af", "Afrikaans", "Afrikaans"],
  ["so", "Somali", "Soomaali"],
  ["ha", "Hausa", "Hausa"],
  ["yo", "Yoruba", "Yorùbá"],
  ["zu", "Zulu", "isiZulu"],
  ["lb", "Luxembourgish", "Lëtzebuergesch"],
];

export const KNOWN_LANGUAGES: KnownLanguage[] = LIST.map(([code, name, native]) => ({ code, name, native, direction: RTL.has(code) ? "rtl" : "ltr" }));
